[package]
name = "hello-cargo"
version = "0.1.0"
authors = ["Clovis Mugaruka <clovis.mugaruka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
